name: Deploy to Server

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Your Application
        run: |
          # Your build commands here
          npm install
          npm run build
      - name: Deploy to Server
        uses: actions/ssh@v3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: 22
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd your_deploy_directory
            # Your deployment commands here
            git pull origin main
            npm run build
            # Restart your server or other deployment steps
