
name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm install
      - name: Build the Application
        run: npm run build
      - name: Deploy to Server
        uses: actions/exec@v3
        with:
          command: |
            ssh -i ~/.ssh/${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd testt && git pull origin main && npm run build && npm run start"
